name: Cloudflare Log Attachment
description: This will attach the pages deploy log to the PR decoration

inputs:
  email:
    description: email address for api key
    required: true
  api-key:
    description: the api key to get access to logs
    required: true
  accountid:
    description: cloudflare account id to retrieve logs from
    required: true
  github-token:
    description: token with enough access to update issue comments
    required: false
    default: ${{ github.token }}


runs:
  using: composite
  steps:
    - name: Cloudflare Log Processing
      shell: bash
      run: ${{ github.action_path }}/logattach.sh
      env:
        EMAIL: ${{ inputs.email }}
        API_KEY: ${{ inputs.api-key }}
        ACCOUNTID: ${{ inputs.accountid }}
        CHECK_URL: ${{ github.event.check_run.url }}
        GH_TOKEN: ${{ inputs.github-token }}
